settings:
  carolina:
    name: Carolina Panthers
    language: en
    staleness: 3h
    news_search_string: Carolina Panthers
    nlp_filter_score: 0.975
    acceptable_news_sources:
      - ESPN.com
      - Carolina Panthers
      - Bleacher Report
      
    verified_news_sources:
      - Carolina Panthers
      - Bleacher Report
    twitter_api:
      client_id: **client_id**
      client_secret: **client_secret**
      api_key: **api_key**
      api_key_secret: **api_key_secret**
      bearer_token: **bearer_token**
      access_token: **access_token**
      access_token_secret: **access_token_secret**
openai_api_key: **openai_api_key**